# Generated by Django 5.1.2 on 2024-10-16 20:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('case_title', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='case_images/')),
                ('signalment', models.TextField()),
                ('history', models.TextField()),
                ('clinical_examination', models.TextField()),
                ('clinical_findings', models.TextField()),
                ('differential_diagnosis', models.TextField()),
                ('tentative_diagnoses', models.TextField()),
                ('management', models.TextField()),
                ('diagnosis_plan', models.TextField()),
                ('advice_to_clients', models.TextField()),
                ('assistants', models.TextField()),
                ('laboratory_results', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
