# Generated by Django 5.1.2 on 2024-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='bookmark_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
    ]
