# Generated by Django 5.1.2 on 2024-10-17 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rename_pub_date_cases_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Surgery', 'Surgery'), ('Medicine', 'Medicine')], max_length=100)),
                ('case_title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_images/')),
                ('signalment_and_history', models.TextField(blank=True, null=True)),
                ('clinical_examination', models.TextField(blank=True, null=True)),
                ('clinical_findings', models.TextField(blank=True, null=True)),
                ('differential_diagnoses', models.TextField(blank=True, null=True)),
                ('tentative_diagnoses', models.TextField(blank=True, null=True)),
                ('management', models.TextField(blank=True, null=True)),
                ('diagnostic_plan', models.TextField(blank=True, null=True)),
                ('advice_to_clients', models.TextField(blank=True, null=True)),
                ('assistants', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
    ]
