# Generated by Django 5.1.2 on 2024-10-16 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Surgery', 'Surgery'), ('Medicine', 'Medicine'), ('Diagnostics', 'Diagnostics')], max_length=50)),
                ('case_title', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='case_images/')),
                ('signalment', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('clinical_examination', models.TextField(blank=True, null=True)),
                ('clinical_findings', models.TextField(blank=True, null=True)),
                ('differential_diagnosis', models.TextField(blank=True, null=True)),
                ('tentative_diagnoses', models.TextField(blank=True, null=True)),
                ('management', models.TextField(blank=True, null=True)),
                ('diagnosis_plan', models.TextField(blank=True, null=True)),
                ('advice_to_clients', models.TextField(blank=True, null=True)),
                ('assistants', models.TextField(blank=True, null=True)),
                ('laboratory_results', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
