# Generated by Django 5.1.2 on 2024-10-16 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_delete_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('emergency', 'Emergency'), ('routine', 'Routine'), ('follow-up', 'Follow-Up')], max_length=50)),
                ('case_title', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='case_images/')),
                ('signalment', models.TextField()),
                ('history', models.TextField()),
                ('clinical_examination', models.TextField()),
                ('clinical_findings', models.TextField()),
                ('differential_diagnosis', models.TextField()),
                ('tentative_diagnoses', models.TextField()),
                ('management', models.TextField()),
                ('diagnosis_plan', models.TextField()),
                ('advice_to_clients', models.TextField()),
                ('assistants', models.TextField()),
                ('laboratory_results', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
