# Generated by Django 5.1.2 on 2024-10-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='user',
        ),
    ]
