# Generated by Django 5.1.2 on 2024-10-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_remove_case_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
