# Generated by Django 5.1.2 on 2024-10-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_delete_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='specialization_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='vcn_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
